FROM python:3.12.7-alpine

WORKDIR /code

COPY backend/microservices/adoption/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8003"]