networks:
  backend-net:

services:
  health-microservice:
    build:
      context: ./backend/microservices/health/
      dockerfile: Dockerfile
    env_file:
      - ./backend/microservices/health/.env
    volumes:
      - ./backend/microservices/health/:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - backend-net
    depends_on:
      - db
      - redis
    
  users-microservice:
    build:
      context: ./backend/microservices/users/
      dockerfile: Dockerfile
    env_file:
      - ./backend/microservices/users/.env
    volumes:
      - ./backend/microservices/users/:/code
    expose:
      - "8001"
    ports:
      - "8001:8001"
    networks:
      - backend-net
    depends_on:
      - db
      - redis
  
  auth-microservice:
    build:
      context: ./backend/microservices/auth/
      dockerfile: Dockerfile
    env_file:
      - ./backend/microservices/auth/.env
    volumes:
      - ./backend/microservices/auth/:/code
    expose:
      - "8002"
    ports:
      - "8002:8002"
    networks:
      - backend-net
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=pffdb
    networks:
      - backend-net

  nginx:
    image: nginx:1.28.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - health-microservice
    networks:
      - backend-net

  redis:
    image: redis:7.4-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - backend-net

  node:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - "5173"
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/pff-react/src:/app/src
      - ./frontend/pff-react/public:/app/public
    depends_on:
      - health-microservice
    networks:
      - backend-net

volumes:
  postgres_data:
  redis_data: