FROM python:3.12.7-alpine

WORKDIR /code

COPY backend/microservices/auth/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/microservices/auth .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]