FROM python:3.12.7-alpine

WORKDIR /code

COPY backend/microservices/users/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/microservices/users .

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]