apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-microservice
  labels:
    app: ai-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-microservice
  template:
    metadata:
      labels:
        app: ai-microservice
    spec:
      imagePullSecrets:
      - name: docker-login
      containers:
      - name: ai-microservice
        image: vladimirsgit/pet-friend-finder:ai-microservice-v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8004
        envFrom:
        - secretRef:
            name: ai-microservice-secrets
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1.5Gi